services:
  lemmy-federation-exporter:
    image: ghcr.io/nothing4you/lemmy-federation-exporter:latest
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "1"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus/config:ro
      - prometheus-data:/prometheus
    command:
      # - '--web.enable-admin-api'
      - '--config.file=/etc/prometheus/config/prometheus.yml'
      - '--storage.tsdb.retention.time=31d'
    logging:
      options:
        max-size: "10m"
        max-file: "1"

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning/:ro
    environment:
      GF_DEFAULT_INSTANCE_NAME: lem.rocks Grafana
      GF_SERVER_DOMAIN: grafana.lem.rocks
      GF_SERVER_ENFORCE_DOMAIN: true
      GF_SERVER_ROOT_URL: https://grafana.lem.rocks/
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: true
      GF_SECURITY_SECRET_KEY: ...
      GF_SECURITY_DISABLE_GRAVATAR: true
      GF_SECURITY_COOKIE_SECURE: true
      GF_SECURITY_COOKIE_SAMESITE: lax
      GF_SECURITY_ALLOW_EMBEDDING: true
      GF_SECURITY_STRICT_TRANSPORT_SECURITY: true
      GF_SECURITY_STRICT_TRANSPORT_SECURITY_MAX_AGE_SECONDS: 63072000
      GF_SECURITY_STRICT_TRANSPORT_SECURITY_SUBDOMAINS: true
      GF_SECURITY_CONTENT_SECURITY_POLICY: true
      GF_SECURITY_ANGULAR_SUPPORT_ENABLED: false
      GF_USERS_ALLOW_SIGN_UP: false
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_HIDE_VERSION: true
      GF_AUTH_BASIC_ENABLED: false
      GF_AUTH_GITHUB_ENABLED: true
      GF_AUTH_GITHUB_CLIENT_ID: 3d0fb7288a146c6e9fec
      GF_AUTH_GITHUB_CLIENT_SECRET: ...
      GF_AUTH_GITHUB_AUTH_URL: https://github.com/login/oauth/authorize
      GF_AUTH_GITHUB_TOKEN_URL: https://github.com/login/oauth/access_token
      GF_AUTH_GITHUB_API_URL: https://api.github.com/user
      GF_AUTH_GITHUB_ALLOW_SIGN_UP: true
      GF_AUTH_GITHUB_ROLE_ATTRIBUTE_PATH: >-
        [login=='Nothing4You'][0] && 'Admin' || 'Viewer'
      GF_AUTH_GITHUB_ROLE_ATTRIBUTE_STRICT: true
      GF_AUTH_GITHUB_ALLOW_ASSIGN_GRAFANA_ADMIN: true
    logging:
      options:
        max-size: "10m"
        max-file: "1"

  caddy:
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    #cap_add:
    #  - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config

volumes:
  prometheus-data:
  grafana-data:
  caddy-data:
  caddy-config:
